### ISSUE TITLE
wrong CC for CUDA complication

### ISSUE THREAD

**Issue by lushl9301** [amirnodehi/Tigr#1]
Hi, I'm reading your paper. I notice that you are using P4000 GPU, which is with compute capability 6.1. However, the compile flag used in the code is SM32.

if you compile it with sm61, the performance should be even better.

will it be possible for you to do the experiments again to see the performance improvements?

Regards

**Comment by zhijia** [comment]
Hi, actually, we did use sm61 for the experiments in the paper. Thanks for making a suggestion anyway.
